apiVersion: v2
name: heart-disease-api
description: Heart Disease Prediction ML API Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ml
  - fastapi
  - heart-disease
  - prediction
maintainers:
  - name: MLOps Team
    email: mlops@example.com
