name: heart-disease-mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas==2.1.4
    - numpy==1.26.2
    - matplotlib==3.8.2
    - seaborn==0.13.0
    - scikit-learn==1.3.2
    - sweetviz==2.3.1
    - ucimlrepo==0.0.3
    - jupyter==1.0.0
    - mlflow==2.9.2
    - skl2onnx==1.16.0
    - onnxruntime==1.16.3
    - joblib==1.3.2
