apiVersion: v1
kind: ConfigMap
metadata:
  name: heart-disease-api-config
  namespace: ml-models
data:
  MODEL_PATH: "/app/packaged_models/pickle/best_model.pkl"
  PREPROCESSOR_PATH: "/app/models/preprocessor.pkl"
  API_VERSION: "1.0.0"
  LOG_LEVEL: "info"
